services:
  - type: web
    name: amazon-recommendation
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python nltk_downloader.py
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
